name = "MacroModelling"
uuid = "687ffad2-3618-405e-ac50-e0f7b9c75e44"
authors = ["Thore Kockerols <mail@thorekockerols.com>"]
version = "0.1.41"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BlockTriangularForm = "adeb47b7-70bf-415a-bb24-c358563e873a"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynarePreprocessor_jll = "23afba7c-24e5-5ee2-bc2c-b42e07f0492a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveFactorization = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Subscripts = "2b7f82d5-8785-4f63-971e-f18ddbeb808e"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
SymPyPythonCall = "bc8888f7-b21e-4b7c-a06a-5d9c9496438c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
ThreadedSparseArrays = "59d54670-b8ac-4d81-ab7a-bb56233e17ab"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[weakdeps]
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[extensions]
StatsPlotsExt = "StatsPlots"
TuringExt = "Turing"

[compat]
ADTypes = "1"
Accessors = "0.1"
Aqua = "0.8"
AxisKeys = "0.2"
BlockTriangularForm = "0.1"
CSV = "0.10"
ChainRulesCore = "1"
Combinatorics = "1"
DataFrames = "1"
DataStructures = "0.18, 0.19"
DifferentiationInterface = "0.6,0.7"
DispatchDoctor = "0.4"
DocStringExtensions = "0.8, 0.9"
DynamicPPL = "0.23 - 0.36"
DynarePreprocessor_jll = "6"
FiniteDifferences = "0.12"
ForwardDiff = "0.10, 1"
JET = "0.7, 0.8, 0.9"
JSON = "0.21"
Krylov = "0.10"
LaTeXStrings = "1"
LineSearches = "7"
LinearAlgebra = "1"
LinearOperators = "2"
LinearSolve = "3"
LoopVectorization = "0.12"
MCMCChains = "6"
MacroTools = "0.5"
MatrixEquations = "2"
NLopt = "0.6, 1"
Optim = "1"
Pigeons = "0.3, 0.4"
Polyester = "0.7"
PrecompileTools = "1"
Preferences = "1"
PythonCall = "0.9"
REPL = "1"
Random = "1"
RecursiveFactorization = "0.2"
Reexport = "1"
RuntimeGeneratedFunctions = "0.5"
SparseArrays = "1"
SpecialFunctions = "2"
StatsPlots = "0.15"
Subscripts = "0.1.3"
Suppressor = "0.2"
SymPyPythonCall = "0.2 - 0.5"
Symbolics = "5, 6"
Test = "1"
ThreadedSparseArrays = "0.2.3"
Turing = "0.30 - 0.39"
Unicode = "1"
Zygote = "0.6, 0.7"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["ADTypes", "Aqua", "JET", "CSV", "DataFrames", "DynamicPPL", "MCMCChains", "LineSearches", "Optim", "Test", "Turing", "Pigeons", "FiniteDifferences", "Zygote", "StatsPlots", "Preferences"]
