name = "MacroModelling"
uuid = "687ffad2-3618-405e-ac50-e0f7b9c75e44"
authors = ["Thore Kockerols <mail@thorekockerols.com>"]
version = "0.1.12"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BlockTriangularForm = "adeb47b7-70bf-415a-bb24-c358563e873a"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynarePreprocessor_jll = "23afba7c-24e5-5ee2-bc2c-b42e07f0492a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ImplicitDifferentiation = "57b37032-215b-411a-8a7c-41a003a55207"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveFactorization = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpeedMapping = "f1835b91-879b-4a3f-a438-e4baacf14412"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Subscripts = "2b7f82d5-8785-4f63-971e-f18ddbeb808e"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
AxisKeys = "^0.2"
BlockTriangularForm = "^0.1"
ChainRulesCore = "^1"
DataStructures = "^0.18"
DocStringExtensions = "^0.9"
DynarePreprocessor_jll = "^6.2"
ForwardDiff = "^0.10"
ImplicitDifferentiation = "^0.2, 0.3"
IterativeSolvers = "^0.9"
JSON = "^0.21"
LaTeXStrings = "^1"
LinearMaps = "^3"
MacroTools = "^0.5"
Plots = "^1.36.3"
RecursiveFactorization = "^0.2"
RuntimeGeneratedFunctions = "^0.5"
SnoopPrecompile = "^1"
SpecialFunctions = "^2"
SpeedMapping = "^0.3"
StatsPlots = "^0.15"
Subscripts = "^0.1"
SymPy = "^1"
Symbolics = "^5"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Aqua", "CSV", "DataFrames", "DynamicPPL", "MCMCChains", "Optimization", "OptimizationNLopt", "OptimizationOptimisers", "Test", "Turing", "FiniteDifferences", "Zygote"]
